import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const RobotoCondensed = localFont({
  src: "./fonts/RobotoCondensed-VariableFont_wght.ttf",
  variable: "--font-robo-cond",
  weight: "100 900",
});
const RobotoCondensedItalic = localFont({
  src: "./fonts/RobotoCondensed-Italic-VariableFont_wght.ttf",
  variable: "--font-robo-ital",
  weight: "100 900",
});
const Raleway = localFont({
  src: "./fonts/Raleway-Italic-VariableFont_wght.ttf",
  variable: "--font-raleway",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Subway Serf",
  description: "Generated by yulya",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="outline-dashed outline-2 outline-offset-2">
      <body
        className={`${RobotoCondensed.variable} ${RobotoCondensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
